merchex/merchex/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from listings import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band_list'),
    path('about/', views.about),
    path('contact/', views.contact),
    path('liste/', views.liste_list, name='liste_list'),
    path('liste/<int:id>/', views.liste_detail, name='liste_detail'),
    path('liste/add/', views.liste_create, name='liste_create'),
    path('liste/<int:id>/change/', views.liste_update, name='liste_update'), 
    path('liste/<int:id>/delete/', views.liste_delete, name='liste_delete'), 
    path('bands/<int:id>/', views.band_detail, name='band_detail'),  # Chemin pour la vue détaillée  
    path('bands/<int:id>/change/', views.band_update, name='band_update'),
    path('bands/<int:id>/delete/', views.band_delete, name='band_delete'),
    path('bands/add/', views.band_create, name='band_create'), 
    path('livre/', views.livre_list, name='livre_list'),
    path('livre/add/', views.livre_create, name='livre_create'),
    path('livre/<int:id>/change/', views.livre_update, name='livre_update'), 
    path('livre/<int:id>/delete/', views.livre_delete, name='livre_delete'), 
    path('student/', views.student_list, name='student_list'),
    path('student/add/', views.student_create, name='student_create'),
    path('student/<int:id>/change/', views.student_update, name='student_update'), 
    path('student/<int:id>/delete/', views.student_delete, name='student_delete')
    
] +static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

merchex/listings/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Band(models.Model):
    #classe pour limiter les choix disponible du champ genre
    class Genre(models.TextChoices):
        HIP_HOP = 'HH', 'Hip Hop'  
        SYNTH_POP = 'SP', 'Synth Pop'  
        ALTERNATIVE_ROCK = 'AR', 'Alternative Rock'
    
    
    name = models.fields.CharField(max_length=100)
    biography = models.fields.CharField(max_length=100)
    year_formed = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2021)])
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    def __str__(self):  
        return self.name#premier champ de la table Liste

class Liste(models.Model):
   
    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=100)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2021)])

    TYPE_CHOICES = [  
        ('Records', 'Disques'),  
        ('Clothing', 'Vêtements'),  
        ('Posters', 'Affiches'),  
        ('Miscellaneous', 'Divers'),  
    ] 
    type = models.fields.CharField(max_length=100)
    
     #Ajout de la clé étrangère band
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)
    
    def __str__(self):  
        return self.title #premier champ de la table Liste
    
class Livre(models.Model):  
    nom = models.CharField(max_length=200)  
    description = models.TextField()  
    prix_unitaire = models.DecimalField(max_digits=10, decimal_places=2)  
    quantite = models.PositiveIntegerField()  
    image = models.ImageField(upload_to='books/images/')  
    date_creation = models.DateTimeField(auto_now_add=True)  
    date_modification = models.DateTimeField(auto_now=True)  

    def __str__(self):  
        return self.nom  


class Etudiant(models.Model):  
    nom = models.CharField(max_length=100)  
    prenom = models.CharField(max_length=100)  
    date_naissance = models.DateField()  
    lieu_naissance = models.CharField(max_length=100)  
    emprunt_date = models.DateTimeField(null=True, blank=True)  # Date d'emprunt  
    retour_date = models.DateTimeField(null=True, blank=True)  # Date de retour  
    livre = models.ForeignKey(Livre, on_delete=models.CASCADE, related_name='emprunts')  

    def __str__(self):  
        return f"{self.prenom} {self.nom}"
    
    
    
    
    
    

merchex/listings/forms.py
from django import forms
from listings.models import Band
from listings.models import Liste
from .models import Livre, Etudiant 


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False, label='Nom')
    email = forms.EmailField(label='Email')
    message = forms.CharField(
        max_length=1000,
        widget=forms.Textarea,
        label='Message'
    )


class BandForm(forms.ModelForm):  
    class Meta:  
        model = Band  
        #fields = '__all__'  # Inclut tous les champs du modèle 
        exclude = ('active', 'official_homepage')  # Exclut ces champs du formulaire  



class ListeForm(forms.ModelForm):  
    class Meta:  
        model = Liste 
        #fields = '__all__'  # Inclut tous les champs du modèle 
        fields = '__all__'  # Inclut tous les champs du modèle



class LivreForm(forms.ModelForm):  
    class Meta:  
        model = Livre  
        fields = '__all__'  

class EtudiantForm(forms.ModelForm):  
    class Meta:  
        model = Etudiant  
        fields = '__all__'

merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from listings.models import Band
from listings.models import Liste
from .models import Livre, Etudiant 
from .forms import EtudiantForm  
from .forms import LivreForm
from django.core.mail import send_mail
from listings.forms import ContactUsForm 
from django.shortcuts import redirect 
from listings.forms import BandForm 
from listings.forms import ListeForm 


def band_list(request):
    bands=Band.objects.all()
    return render(request, 'listings/band_list.html', {'bands': bands})  # Envoi des données au gabarit 

# listings/views.py  
def band_detail(request, id):  
    band = Band.objects.get(id=id)  # Récupère l'objet Band avec l'id spécifié  
    return render(request, 'listings/band_detail.html', {'band': band}) 

def liste_list(request):  
    liste = Liste.objects.all()  # Récupération de toutes les annonces  
    return render(request, 'listings/liste_list.html', {'liste': liste})  # Rendu avec le gabarit

def liste_detail(request, id):  
    liste = Liste.objects.get(id=id)  # Récupération de toutes les annonces  
    return render(request, 'listings/liste_detail.html', {'liste': liste})  # Rendu avec le gabarit  

def about(request):  
    return render(request, 'listings/about.html')  # Rendu de la page 'about'

def contact(request):  
    if request.method == 'POST':
        # créer une instance de notre formulaire et le remplir avec les données POST
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
            subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
            message=form.cleaned_data['message'],
            from_email=form.cleaned_data['email'],
            recipient_list=['admin@merchex.xyz'],
        )
            return redirect('email-sent')  # ajoutez cette instruction de retour
    # si le formulaire n'est pas valide, nous laissons l'exécution continuer jusqu'au return
    # ci-dessous et afficher à nouveau le formulaire (avec des erreurs).

        else: 
        # ceci doit être une requête GET, donc créer un formulaire vide
         form = ContactUsForm()  # Instanciation du formulaire  
        return render(request, 'listings/contact.html', {'form': form})  # Passage du formulaire au modèle
    

def band_create(request):  
     if request.method == 'POST':  
        form = BandForm(request.POST)  
        if form.is_valid():  
            band = form.save()  # Sauvegarde le nouvel objet Band  
            return redirect('band_detail', band.id)  # Redirection vers la page de détail du groupe  
     else:  
        form = BandForm()  # Formulaire vide pour une requête GET  

     return render(request, 'listings/band_create.html', {'form': form})



def liste_create(request):  
    if request.method == 'POST':  
        form = ListeForm(request.POST)  
        if form.is_valid():  
            liste = form.save()  # Sauvegarde le nouvel objet Liste  
            return redirect('liste_detail', liste.id)  # Redirection vers la page de détail de la liste  
    else:  
        form = ListeForm()  # Formulaire vide pour une requête GET  

    return render(request, 'listings/liste_create.html', {'form': form})

def band_update(request, id):
    band = Band.objects.get(id=id)

    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('band_detail', band.id)
    else:
        form = BandForm(instance=band)

    return render(request,
                'listings/band_update.html',
                {'form': form})

def liste_update(request, id):
    liste = Liste.objects.get(id=id)

    if request.method == 'POST':
        form = ListeForm(request.POST, instance=liste)
        if form.is_valid():
            # mettre à jour l'annonce existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('liste_detail', liste.id)
    else:
        form = BandForm(instance=liste)

    return render(request,
                'listings/liste_update.html',
                {'form': form})


def band_delete(request, id):
    band = Band.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        band.delete()
        # rediriger vers la liste des groupes
        return redirect('band_list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request,
                    'listings/band_delete.html',
                    {'band': band})


def liste_delete(request, id):
    liste = Liste.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        liste.delete()
        # rediriger vers la liste des groupes
        return redirect('band_list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request,
                    'listings/liste_delete.html',
                    {'liste': liste})






def livre_list(request):  
    livre = Livre.objects.all()  # Récupération de toutes les annonces  
    return render(request, 'listings/livre_list.html', {'livre': livre})  # Rendu avec le gabarit



def livre_create(request):  
    if request.method == 'POST':  
        form = LivreForm(request.POST)  
        if form.is_valid():  
            livre = form.save()  # Sauvegarde le nouvel objet Liste  
            return redirect('livre_list')  # Redirection vers la page de liste des livres
    else:  
        form = LivreForm()  # Formulaire vide pour une requête GET  

    return render(request, 'listings/livre_create.html', {'form': form})

def livre_update(request, id):
    livre = Livre.objects.get(id=id)

    if request.method == 'POST':
        form = LivreForm(request.POST, instance=livre)
        if form.is_valid():
            form.save()  # Sauvegarde les changements
            return redirect('livre_list')  # Redirige vers la liste des livres
    else:
        form = LivreForm(instance=livre)

    return render(request, 'listings/livre_update.html', {'form': form})

def livre_delete(request, id):
    livre = Livre.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        livre.delete()  # Supprime le livre
        return redirect('livre_list')  # Redirige vers la liste des livres

    return render(request, 'listings/livre_delete.html', {'livre': livre})



def student_list(request):  
    student = Etudiant.objects.all()  # Récupération de toutes les annonces  
    return render(request, 'listings/student_list.html', {'student': student})  # Rendu avec le gabarit



def student_create(request):  
    if request.method == 'POST':  
        form = EtudiantForm(request.POST)  
        if form.is_valid():  
            student = form.save()  # Sauvegarde le nouvel objet Liste  
            return redirect('student_list', student.id)  # Redirection vers la page de détail de la liste  
    else:  
        form = EtudiantForm()  # Formulaire vide pour une requête GET  

    return render(request, 'listings/student_create.html', {'form': form})

def student_update(request, id):
    student = Etudiant.objects.get(id=id)

    if request.method == 'POST':
        form = EtudiantForm(request.POST, instance=student)
        if form.is_valid():
            # mettre à jour l'annonce existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('student_list', student.id)
    else:
        form = EtudiantForm(instance=student)

    return render(request,
                'listings/student_update.html',
                {'form': form})

def student_delete(request, id):
    student = Etudiant.objects.get(id=id)  # nécessaire pour GET et pour POST

    if request.method == 'POST':
        # supprimer le groupe de la base de données
        student.delete()
        # rediriger vers la liste des groupes
        return redirect('student_list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement

    return render(request,
                    'listings/student_delete.html',
                    {'student': student})

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

    {% block content %}
    <h1>À Propos de Nous</h1>  
    <p>Ceci est la page à propos.</p>  
    {% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}  

{% block content %}  
     <h1>Supprimer le groupe</h1>  
     <p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p> <!-- Confirmation de la suppression -->  

     <form action="" method="post"> <!-- Formulaire de confirmation -->  
        {% csrf_token %}  
        <input type="submit" value="Supprimer"> <!-- Bouton pour confirmer la suppression -->  
        </form>  
{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}  
{% block content %}  
<h2>{{ band.name }}</h2> <!-- Affiche le nom du groupe -->  
<ul>  
    <li>Genre : {{ band.get_genre_display }}</li> <!-- Affiche le genre du groupe -->  
    <li>Année de formation : {{ band.year_formed }}</li> <!-- Affiche l'année de formation -->  
    <li>Actif : {{ band.active|yesno:"Yes,No" }}</li> <!-- Indique si le groupe est actif -->  
    {% if band.official_homepage %}  
        <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li> <!-- Lien vers la page officielle -->  
    {% endif %}  
</ul>  
<p>{{ band.biography }}</p> <!-- Affiche la biographie du groupe -->  

<a href="{% url 'band_update' band.id %}">Modifier ce groupe</a> <!-- Lien vers le formulaire de modification -->  

<a href="{% url 'band_list' %}">Retourner à la liste des groupes</a> <!-- Lien pour retourner à la liste -->  
{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}  

{% block content %}  
<h1>Groupes</h1>  
<a href="{% url 'band_create' %}">Créer un nouveau groupe</a> <!-- Lien pour créer un groupe -->  
<table>  
    <thead>  
        <tr>  
            <th>Nom</th>  
            <th>Biographie</th>  
            <th>Année de formation</th>  
            <th>Actions</th>  
        </tr>  
    </thead>  
    <tbody>  
        {% for band in bands %}  
        <tr>  
            <td><a href="{% url 'band_detail' band.id %}">{{ band.name }}</a></td> <!-- Lien vers le détail du groupe -->  
            <td>{{ band.biography }}</td> <!-- Affiche la biographie -->  
            <td>{{ band.year_formed }}</td> <!-- Affiche l'année de formation -->  
            <td>  
                <a href="{% url 'band_update' band.id %}">[modifier]</a> <!-- Lien pour modifier le groupe -->  
                <a href="{% url 'band_delete' band.id %}">[supprimer]</a> <!-- Lien pour supprimer le groupe -->  
            </td>  
        </tr>  
        {% endfor %}  
    </tbody>  
</table>  
{% endblock %}

merchex/listings/templates/listings/liste_create.html
{% extends 'listings/base.html' %}  

{% block content %}  
    <h1>Créer une nouvelle annonce</h1>  
    <form action="" method="post" >  
        {% csrf_token %}  
        {{ form.as_p }}  <!-- Génère le formulaire -->  
        <input type="submit" value="Envoyer">  
    </form>  
{% endblock %}

merchex/listings/templates/listings/liste_list.html
{% extends 'listings/base.html' %}

    {% block content %}
    <h1>Liste des Annonces</h1>  
    <ul>  
        {% for liste in liste %}  
            <a href="{% url 'liste_detail' liste.id%}"><li>{{ liste.title }}</li></a>  <!-- Affiche le titre de chaque annonce -->  
            <a href="{% url 'liste_update' liste.id %}">[modifier]</a>
            <a href="{% url 'liste_delete' liste.id %}">[supprimer]</a>
        {% endfor %}  
    </ul>  
    <h1>Groupes</h1>  
          <a href="{% url 'liste_create' %}">Créer une nouvelle annonce</a>
    {% endblock %}

merchex/listings/templates/listings/livre_create.html
{% extends 'listings/base.html' %}




{% block content %}

<h1>Ajouter un Livre</h1>  
    <form method="post" enctype="multipart/form-data">  
        {% csrf_token %}  
        {{ form.as_p }}  
        <button type="submit">Ajouter</button>  
    </form>  
    <a href="{% url 'livre_list' %}">Retour à la Liste des Livres</a>  















{% endblock %}

merchex/listings/templates/listings/livre_delete.html
{% extends 'listings/base.html' %}  

{% block content %}  
     <h1>Supprimer l'annonce</h1>
     <p>Etes-vous sûr de vouloir supprimer l'annonce : {{ livre.name }} ?</p> 

     <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Supprimer">
        </form>
{% endblock %}

merchex/listings/templates/listings/livre_list.html
{% extends 'listings/base.html' %}  

{% block content %}  
<h1>Liste des Livres</h1>  

<table>  
    <thead>  
        <tr>  
            <th>Nom</th>  
            <th>Description</th>  
            <th>Prix</th>  
            <th>Quantité</th>  
            <th>Image</th>  
            <th>Actions</th>  
        </tr>  
    </thead>  
    <tbody>  
        {% for livre in livre %}  
        <tr>  
            <td>{{ livre.nom }}</td>  
            <td>{{ livre.description }}</td>  
            <td>{{ livre.prix_unitaire }}FCFA</td>  
            <td>{{ livre.quantite }}</td>  
            <td>  
                <img src="{{ livre.image.url }}" alt="{{ livre.nom }}" style="width:100px;height:auto;">  
            </td>  
            <td>  
                <a href="{% url 'livre_update' livre.id %}">Modifier</a>  
                <a href="{% url 'livre_delete' livre.id %}">Supprimer</a>   
            </td>  
        </tr>  
        {% endfor %}  
    </tbody>  
</table>  

<a href="{% url 'livre_create' %}">Ajouter un Livre</a>  
{% endblock %} 

merchex/listings/templates/listings/livre_update.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Mise à jour de l'annonce</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>
    <a href="{% url 'livre_list' %}">Retour à la liste des groupes</a>
{% endblock %}

merchex/listings/templates/listings/student_create.html
{% extends 'listings/base.html' %}  

{% block content %}  
    <h1>Créer une nouvelle annonce</h1>  
    <form action="" method="post" >  
        {% csrf_token %}  
        {{ form.as_p }}  <!-- Génère le formulaire -->  
        <input type="submit" value="Envoyer">  
    </form>  
{% endblock %}

merchex/listings/templates/listings/student_delete.html
{% extends 'listings/base.html' %}  

{% block content %}  
     <h1>Supprimer le livre</h1>
     <p>Etes-vous sûr de vouloir supprimer cet étudiant ? : {{ student.nom }} ?</p> 

     <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Supprimer">
        </form>
{% endblock %}

merchex/listings/templates/listings/student_list.html
{% extends 'listings/base.html' %}


 {% block content %}
 <h1>Liste des Etudiants</h1>  
    

 <table>  
    <thead>  
        <tr>  
            <th>Nom</th>  
            <th>Prenom</th>  
            <th>Date Naissance</th>  
            <th>Lieu de Naissance</th>    
            <th>Livre Emprunté</th>    
            <th>Image du livre</th>    
            <th>Action</th>    
        </tr>  
    </thead>  
    <tbody>  
        {% for student in student %}  
        <tr>  
            <td>{{ student.nom }}</td>  
            <td>{{ student.prenom }}</td>  
            <td>{{ student.date_naissance }}</td>  
            <td>{{ student.lieu_naissance }}</td>  
            <td>{{ student.livre }}</td>  
            <td>  
                <img src="{{ student.livre.image.url }}" alt="{{ livre.nom }}" style="width:100px;height:auto;">  
            </td>  
            <td>  
                <a href="{% url 'student_update' student.id %}">Modifier</a>  
                <a href="{% url 'student_delete' student.id %}">Supprimer</a>   
            </td>  
        </tr>  
        {% endfor %}  
    </tbody>  
</table>  

<a href="{% url 'student_create' %}">Ajouter un Etudiant</a> 





























    {% endblock %}

merchex/listings/templates/listings/student_update.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Mise à jour de l'annonce</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>
    <a href="{% url 'student_list' %}">Retour à la liste des livres</a>
{% endblock %}